[package]
name = "lls"
version = "0.1.0"
edition = "2021"
authors = ["Julius Michaelis <gitter@liftm.de>"]
repository = "https://github.com/jcaesar/lls"
license = "MIT"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.66"
itertools = "0.10.5"
netlink-packet-core = "0.4.2"
netlink-packet-route = "0.13.0"
netlink-packet-sock-diag = "0.4.0"
netlink-sys = "0.8.3"
procfs = "0.14.1"
terminal_size = "0.2.2"
unicode-width = "0.1.10"
users = "0.11.0"

[profile.release]
lto = "fat"
strip = "debuginfo"
