[package]
name = "tols"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
comfy-table = "6.1.0"
itertools = "0.10.5"
netlink-packet-sock-diag = "0.4.0"
netlink-sys = "0.8.3"
procfs = "0.14.1"
